### ISSUE TITLE
scusi sa l'ora?

### ISSUE THREAD

**Issue by plspeziali** [DiegoArcelli/Gioco-della-vita#1]
ma che ore sono? mezzogiorno e mezza, quando ero a scuola volevo solo pasta vado in cucina sembro uno chef

**Comment by DiegoArcelli** [comment]
Cari ascoltatori la conferma dello stato tirannico asimmetrico... NOI LI DOBBIAMO PAGARE SEMPRE GLI INTERESSI DI MORA SULLE TASSE SE SIAMO IN RITARDO, LO STATO SI COSTRUISCE UNA SENTENZA DOVE NON LO FA ED È PER RIGORE PUBBLICO. **È UNO STATO LADRO, LADRO, LADRO, LADROOOOOOOOOOOOOOO**
