### ISSUE TITLE
non chiudere le issues che fa caldo fa passa l'aria

### ISSUE THREAD

**Issue by plspeziali** [DiegoArcelli/Gioco-della-vita#2]
uff pant pant che calor

**Comment by DiegoArcelli** [comment]
![marizilio](https://user-images.githubusercontent.com/28904815/82792509-d1677c00-9e6f-11ea-9b89-bbdb2aa227b0.jpg)

Che vol dì alorca?

**Comment by plspeziali** [comment]
aspetta che chiedo... aspetta l mi fratello... BUUURP
